load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository", "new_git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")


new_git_repository(
    name = "fdsdk",
    remote = "file:///home/pedro/tmp/toolchain/freedesktop-sdk-toolchain",
    branch = "master",
    build_file = 'fdsdk.BUILD'
)

http_archive(
  name = "fdsdk-tar",
  urls = [
       "file:///home/pedro/tmp/toolchain/freedesktop-sdk-toolchain.tar.xz",
  ],
  build_file = 'fdsdk.BUILD'
)

