load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")


git_repository(
    name = "fdsdk-git",
    remote = "file:///home/pedro/tmp/toolchain/freedesktop-sdk-toolchain",
    tag = "master",
)

http_archive(
  name = "fdsdk",
  urls = [
       "file:///home/pedro/tmp/toolchain/freedesktop-sdk-toolchain.tar.xz",
  ],
  build_file = 'fdsdk.BUILD'
)

